"""Delete characteristics

Revision ID: 634f23dc4b77
Revises: 9ac21c3870cc
Create Date: 2024-05-23 17:16:30.608383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '634f23dc4b77'
down_revision: Union[str, None] = '9ac21c3870cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characteristics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characteristics',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='characteristics_pkey')
    )
    # ### end Alembic commands ###
