"""Update Product an rand relations

Revision ID: e19d67748ec2
Revises: baf7d55b8c1e
Create Date: 2024-05-24 14:11:31.637400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e19d67748ec2'
down_revision: Union[str, None] = 'baf7d55b8c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
