"""has_children attr at categories is required

Revision ID: 8ad9a09926d4
Revises: 2a02f4530f33
Create Date: 2024-05-29 12:33:02.429581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ad9a09926d4'
down_revision: Union[str, None] = '2a02f4530f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'has_children',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'has_children',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
