"""Product model updated

Revision ID: ab735c59efbe
Revises: c7af03c86f9f
Create Date: 2024-05-23 16:01:38.957748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab735c59efbe'
down_revision: Union[str, None] = 'c7af03c86f9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('characteristics_list', sa.Integer(), nullable=False))
    op.alter_column('products', 'image_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('products_characteristics_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'characteristics', ['characteristics_list'], ['id'])
    op.drop_column('products', 'characteristics_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('characteristics_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_characteristics_id_fkey', 'products', 'characteristics', ['characteristics_id'], ['id'])
    op.alter_column('products', 'image_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('products', 'characteristics_list')
    # ### end Alembic commands ###
