"""Added has_children attr to categories

Revision ID: 2a02f4530f33
Revises: ebfde7c05627
Create Date: 2024-05-29 12:23:10.148932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a02f4530f33'
down_revision: Union[str, None] = 'ebfde7c05627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('has_children', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'has_children')
    # ### end Alembic commands ###
