"""Removed has_children and level from Categories

Revision ID: e58a28728f9c
Revises: 8ad9a09926d4
Create Date: 2024-05-29 15:57:33.642572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e58a28728f9c'
down_revision: Union[str, None] = '8ad9a09926d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'has_children')
    op.drop_column('categories', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('categories', sa.Column('has_children', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
