"""Added autoincrement to Base id

Revision ID: a768ef5ef1b8
Revises: d6bc6c120676
Create Date: 2024-05-31 14:48:10.027281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a768ef5ef1b8'
down_revision: Union[str, None] = 'd6bc6c120676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
