"""Create Category, Brands, Characteristics, Images tables

Revision ID: 59a6cd35d33e
Revises: 0f77bd84c1ac
Create Date: 2024-05-22 17:35:16.500109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '59a6cd35d33e'
down_revision: Union[str, None] = '0f77bd84c1ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('categories',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('level', sa.Integer(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('parent_id', sa.Integer(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('characteristics',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('value_type', sa.String(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('images',
                    sa.Column('url', sa.String(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('image_id', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('brand_id', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('characteristics_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'brands', ['brand_id'], ['id'])
    op.create_foreign_key(None, 'products', 'characteristics', ['characteristics_id'], ['id'])
    op.create_foreign_key(None, 'products', 'images', ['image_id'], ['id'])
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'characteristics_id')
    op.drop_column('products', 'brand_id')
    op.drop_column('products', 'image_id')
    op.drop_column('products', 'category_id')
    op.drop_table('images')
    op.drop_table('characteristics')
    op.drop_table('categories')
    op.drop_table('brands')
    # ### end Alembic commands ###
