"""Update Product - deleted availability field

Revision ID: 6843d01044ac
Revises: aec2b89aa7ee
Create Date: 2024-05-24 11:50:07.009194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6843d01044ac'
down_revision: Union[str, None] = 'aec2b89aa7ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'availability')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('availability', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
