"""Updated Characteristics

Revision ID: 9ac21c3870cc
Revises: ab735c59efbe
Create Date: 2024-05-23 17:14:52.151814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac21c3870cc'
down_revision: Union[str, None] = 'ab735c59efbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('age', sa.String(), nullable=True))
    op.add_column('products', sa.Column('main_ingredient', sa.String(), nullable=True))
    op.add_column('products', sa.Column('special_prescription', sa.String(), nullable=True))
    op.add_column('products', sa.Column('country_of_origin', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('packed_in', sa.String(), nullable=True))
    op.add_column('products', sa.Column('qty_in_package', sa.String(), nullable=True))
    op.add_column('products', sa.Column('weight', sa.String(), nullable=True))
    op.add_column('products', sa.Column('length', sa.String(), nullable=True))
    op.add_column('products', sa.Column('width', sa.String(), nullable=True))
    op.add_column('products', sa.Column('height', sa.String(), nullable=True))
    op.add_column('products', sa.Column('availability', sa.String(), nullable=True))
    op.drop_constraint('products_characteristics_list_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'characteristics_list')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('characteristics_list', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('products_characteristics_list_fkey', 'products', 'characteristics', ['characteristics_list'], ['id'])
    op.drop_column('products', 'availability')
    op.drop_column('products', 'height')
    op.drop_column('products', 'width')
    op.drop_column('products', 'length')
    op.drop_column('products', 'weight')
    op.drop_column('products', 'qty_in_package')
    op.drop_column('products', 'packed_in')
    op.drop_column('products', 'country_of_origin')
    op.drop_column('products', 'special_prescription')
    op.drop_column('products', 'main_ingredient')
    op.drop_column('products', 'age')
    # ### end Alembic commands ###
